### Ensuring Consistency Across Training & Inference Datasets: Feature Scaling
**Question**: Load a dataset (e.g., Boston Housing) and perform feature scaling. Ensure the
same scaling is applied during model inference with new data.

In [1]:
# write your code from here
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#SimulateaDataset(replacingBostonHousing)
np.random.seed(42)
num_samples=100
num_features=5
X=np.random.rand(num_samples,num_features)*100+np.random.randn(num_samples,num_features)*10
y=np.random.rand(num_samples)*1000

#Splitthedatainto"training"and"new/inference"sets
X_train,X_new_inference,y_train,y_new_inference=train_test_split(X,y,test_size=0.3,random_state=42)

#InitializeandFitthescalerontheTRAININGDATAONLY
scaler=StandardScaler()
scaler.fit(X_train)

#TransformtheTRAININGDATA
X_train_scaled=scaler.transform(X_train)

#Simulatenew/inference_data(usingX_new_inferencefromsplit)
#ThisX_new_inferenceisour"newdata"thatthemodelwillseeindatainference
print("OriginalX_new_inference(first5rows):\n",X_new_inference[:5])

#TransformtheNEW/INFERENCEDATAusingtheSAMEFITTEDSCALER
X_new_inference_scaled=scaler.transform(X_new_inference)

print("\nScaledX_train(first5rows):\n",X_train_scaled[:5])
print("\nScaledX_new_inference(first5rows):\n",X_new_inference_scaled[:5])

#Verifythatthescalerparameters(meanandstd)arethesameforboth
#Thisimplicitlyshowsthesamescalingisapplied
print("\nScalerMean(fromtrainingdata):\n",scaler.mean_)
print("ScalerStandardDeviation(fromtrainingdata):\n",scaler.scale_)

OriginalX_new_inference(first5rows):
 [[ 39.68410492  30.28228494  28.24370165  62.90688333  72.14573171]
 [ 85.34251207  67.01268719  59.18314931  61.68271315  29.95136877]
 [ 52.8739232   95.47589396  82.52410761  26.43714336 -11.35186757]
 [ 23.84311763 100.10074174  28.05488199 113.66217531  64.40607442]
 [ 58.02339724  44.3843133   -8.41972571  51.73202342  33.06389333]]

ScaledX_train(first5rows):
 [[ 1.23446871 -1.85147512 -0.99705371 -1.89155453 -0.08348963]
 [ 0.8077672  -0.08540924 -1.08999129  0.87866696 -0.85767102]
 [ 0.05163815  0.26722702  1.37568803 -0.2128853  -1.31547336]
 [ 0.89394638 -0.72414772  0.11027559 -0.97127207 -0.21023228]
 [-0.48166899 -0.82825855  1.63968517 -0.4882022   1.41031699]]

ScaledX_new_inference(first5rows):
 [[-0.25968352 -0.58510621 -0.68290296  0.33171932  0.87340572]
 [ 1.04781659  0.51954945  0.33628987  0.29361615 -0.35322032]
 [ 0.11802761  1.37557173  1.10517682 -0.80342733 -1.55394054]
 [-0.71331504  1.51466262 -0.68912297  1.91151396 