### Ensuring Consistency Across Training & Inference Datasets: Pipeline Integration
**Question**: Create and train a machine learning pipeline that ensures feature transformation consistency across training and inference datasets using scikit-learn.

In [1]:
# write your code from here
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
#SimulateaDataset
X,y=make_classification(n_samples=1000,n_features=20,n_informative=10,n_redundant=10,random_state=42)
#SplitthedataintoTrainingandTestsets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
#CreateaPipeline:ScalingfollowedbyLogisticRegression
pipeline=Pipeline([
('scaler',StandardScaler()),
('classifier',LogisticRegression(random_state=42))
])
#Trainthepipelineonthetrainingdata
#Thescalerwillbefittedandtransformedhereautomatically
pipeline.fit(X_train,y_train)
print("PipelineFittedSuccessfully.")
#Now,use thetrainedpipelineforinferenceonnewdata(X_test)
#Thescaler'stransformation(fittedonX_train)willbeautomaticallyappliedtoX_test
y_pred=pipeline.predict(X_test)
print("\nPredictionsonTestData(first10):")
print(y_pred[:10])
#Demonstrateinternaltransformation(optional,forunderstanding)
#Accessingthefittedscalerfromthepipeline
fitted_scaler=pipeline.named_steps['scaler']
#YoucanmanuallytransformX_testtoseeitmatcheswhatpipelineinternallydoes
X_test_scaled_manually=fitted_scaler.transform(X_test)
print("\nFirstrowofOriginalX_test:\n",X_test[0][:5])
print("\nFirstrowofScaledX_test(internalpipelineor_manually):\n",X_test_scaled_manually[0][:5])
#Thekeyisthatyouonlycall.fit()onthetrainingdata,and.transform()or.predict()
#onthenewdata,usingthesametrainedsampler.

PipelineFittedSuccessfully.

PredictionsonTestData(first10):
[1 1 0 0 0 1 1 1 1 1]

FirstrowofOriginalX_test:
 [-1.37048697 -4.19982289  2.9717728  -2.72995437  0.64632591]

FirstrowofScaledX_test(internalpipelineor_manually):
 [-0.71387952 -1.08076659  0.53009656 -1.03045976  0.06215994]
